# =============================================================================
# ingestion.py
# Author: Henry Boyes
# Institution: Cleveland Clinic
# Date: 2/18/2026
# Contact: boyeshenry@gmail.com
# Description: This script takes in .QPTIFF files generated by the Akoya PCF instrument and extracts the metadata from them.
# It saves the metadata in a database for downstream analysis.
# =============================================================================

import os
import tifffile
import sqlite3
import argparse
import xml.etree.ElementTree as ET
from datetime import datetime
from utils import setup_logging

ISILON_BASE = os.environ.get("AKOYA_ISILON")
DB_PATH = os.environ.get("AKOYA_DB")
SLURM_ARRAY = os.environ.get("SLURM_ARRAY_TASK_ID")
if SLURM_ARRAY:
    SLURM_ARRAY = int(SLURM_ARRAY)

parser = argparse.ArgumentParser(description="Project folder name")
parser.add_argument("--project", required=True, type=str, help="Enter the project folder name (case sensitive)")
parser.add_argument("--run_date", required=False, type=str, help="""Enter the date the run was performed. 
If unsure of the run date, check the file name.""" )
parser.add_argument("--panel_config", default="configs/io60_panel_config.json", type=str, 
help="Path to panel config JSON for cluster annotation")
args = parser.parse_args()

def scan_for_files(base_path):
    """
    Scan base_path for QPTIFF files and returns a list of file paths
    """
    file_path = []

    # Ensure file exists

    if not os.path.exists(base_path):
        print('Folder not found!')
        return []

    # Find .qptiff files in the folder

    for root, dirs, files in os.walk(base_path):
        for file in files:
            if file.endswith(".qptiff"):
                full_path = os.path.join(root, file)
                file_path.append(full_path)

    file_path.sort()
    
    return file_path

def extract_metadata(file_path):
    """
    Extract metadata from a QPTIFF file. Returns a dict.
    """

    with tifffile.TiffFile(file_path) as tif:
        t_series = tif.series[0]
        meta = ET.fromstring(tif.pages[0].description)
        slide = meta.find("SlideID").text

        markers = []
        for page in tif.series[0].pages:
            meta = ET.fromstring(page.description)
            names = meta.find('Name')
            if names is not None:
                markers.append(names.text)
            
    meta_dict = {
        'file_path': file_path,
        'file_name': os.path.basename(file_path),
        'slide_id': slide,
        'num_channels': t_series.shape[0],
        'markers': markers,
        'image_shape': t_series.shape[1:]
    }

    return meta_dict   

def validate_file(metadata):
    """
    Check metadata for completeness. Returns (bool, str) - valid message.
    """
    if not metadata['file_path']:
        return (False, "Missing file path")
    
    elif not metadata["file_name"]:
        return (False, "Missing file name")

    elif not metadata["slide_id"]:
        return (False, "Missing slide ID")
    
    elif not metadata['num_channels']:
        return (False, "Missing number of channels")
    
    elif not metadata['markers']:
        return (False, "Missing marker names")

    elif metadata['num_channels'] != len(metadata['markers']):
        return (False, "Number of channels does not match number of markers")

    elif not metadata['image_shape']:
        return (False, "Missing image dimensions")
    
    return (True, "All checks passed!")
    

def write_to_db(cursor, metadata, run_id=None):
    """
    Write a validated file record to the Database.
    """

    cursor.execute("SELECT COUNT(*) FROM slides WHERE file_path = ?", (metadata['file_path'],))
    count = cursor.fetchone()[0]

    if count == 0:
        try:
            cursor.execute("insert into slides (slide_name, file_path, file_name, num_channels, run_id) values (?, ?, ?, ?, ?)",
            (metadata['slide_id'], metadata['file_path'], metadata['file_name'], metadata['num_channels'], run_id))
            slide_id = cursor.lastrowid
            cursor.execute("""INSERT INTO pipeline_status (slide_id, ingestion, preprocessing_qc, segmentation, feature_extraction, 
            anndata_export, phenotyping, spatial_analysis) 
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)""", 
            (slide_id, 'Complete', 'Not Started', 'Not Started', 'Not Started', 'Not Started', 'Not Started', 'Not Started'))
        except Exception as e:
            raise
        
    else:
        logger.info(f"Skipping {metadata['file_name']}: Already in DataBase")
    
    return

def write_run(cursor, run_name, panel_config, run_date):
    """
    This function writes the run data to the database

    : ARGS :

    cursor : sqlite3 obj
        The sqlite3 cursor to the database
    
    run_name : str
        The project/run name
    
    panel_config : str
        The antibody panel used for the run

    run_date : datetime
        The date the run was performed
    """
    cursor.execute("SELECT run_id FROM runs WHERE run_name = ? AND run_date = ?", (run_name, run_date))
    row = cursor.fetchone()

    if row:
        run_id = row[0]
    else:
        try:
            cursor.execute("INSERT INTO runs (run_name, panel_name, run_date) values (?, ?, ?);",
            (run_name, panel_config, run_date))
            run_id = cursor.lastrowid
        except Exception as e:
            raise

    return run_id


    
if __name__ == "__main__":
    start_time = datetime.now()
    folder_name = args.project
    run_date = args.run_date
    panel_config = args.panel_config
    db_path = DB_PATH
    project_path = f"{ISILON_BASE}/{folder_name}"

    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    
    log_dir = os.path.join(project_path, 'logs')
    os.makedirs(log_dir, exist_ok=True)

    logger = setup_logging(folder_name, log_dir)
    
    logger.info("Scanning for files...")
    files = scan_for_files(f"{ISILON_BASE}/{folder_name}")
    logger.info(f"Found {len(files)} files")

    if SLURM_ARRAY:
        files = [files[SLURM_ARRAY]]

    for file in files:
        try:
            logger.info(f"Processing {os.path.basename(file)}...")
            if run_date:
                run_id = write_run(cursor, folder_name, panel_config, run_date)
            else:
                run_id=None
                logger.info("Run information not entered")
            metadata = extract_metadata(file)
            valid, message = validate_file(metadata)
            if valid:
                write_to_db(cursor, metadata, run_id)
            else:
                logger.info(f"Skipping {os.path.basename(file)}: {message}")
            
        except Exception as e:
            logger.error(f"Slide {os.path.basename(file)} failed", exc_info=True)

    conn.commit()
    conn.close()

    end_time  = datetime.now() - start_time
    logger.info(f"Done! Finished in {end_time}")