# =============================================================================
# segmentation.py
# Author: Henry Boyes
# Institution: Cleveland Clinic
# Date: 3/5/2026
# Version: v0.1.01
# Contact: boyeshenry@gmail.com
# Description: This script takes in .QPTIFF files generated by the Akoya PCF instrument and creates a mask of the image. 
# It extracts the DAPI channel then uses Cellpose segmentation. It outputs a mask which is saved in the project directory.
# =============================================================================

import os
import numpy as np
import tifffile
import sqlite3
import argparse
from datetime import datetime
from cellpose import models
from utils import is_already_processed
from ingestion import scan_for_files

tile_size = 2048
tile_overlap = 256

ISILON_BASE = os.environ.get("AKOYA_ISILON")
DB_PATH = os.environ.get("AKOYA_DB")

parser = argparse.ArgumentParser(description="Project folder name and cell diameter")
parser.add_argument("--project", required=True, type=str, help="Enter the project folder name (case sensitive)")
parser.add_argument("--diameter", default=None, type=float, help="Enter the diameter of the cells (if known). Default is 0")
args = parser.parse_args()

def extract_dapi_channel(file_path):
    """
    This function extracts the DAPI channel from the image. It returns an array of the DAPI channel.

    : ARGS : 
    
    file_path : str
        The path to the tifffile
    
    : RETURNS : 

    DAPI : array
        An array of the DAPI channel
    """

    with tifffile.TiffFile(file_path) as tif:
        series = tif.series[0]
        dapi = series.pages[0].asarray()

    return dapi

def tile_image(channel_array):
    """
    This function takes in a channel array and tiles it. It returns a list of dicts.

    : ARGS :

    channel_array : array
        An array of the channel being tiled

    : RETURNS : 

    tile_dict : dict
        A dictionary of tile information
    """

    dimension = channel_array.shape
    res = []

    for h in range(0, dimension[0], tile_size - tile_overlap):
        for w in range(0, dimension[1], tile_size - tile_overlap):
            channel_slice = channel_array[h: h + tile_size, w: w+tile_size]
            tile_dict = {
                "array" : channel_slice,
                "row_start" : h,
                "row_stop" : min(h + tile_size, dimension[0]),
                "col_start" : w,
                "col_stop": min(w + tile_size, dimension[1])
            }

            res.append(tile_dict)
    return res

## Set up cellpose
model = models.CellposeModel(gpu=False)

def detect_cells(tiles):
    """
    This function takes a tile and detects the cells in that tile.

    : ARGS :
    
    tiles : list
        The list of dicts of the tiles
    """
    res = []
    
    for tile in tiles:
        masks, flows, styles = model.eval(tile['array'], diameter=args.diameter)
        cell_dict = {
            'mask': masks,
            'flow': flows,
            'style': styles,
            "row_start" : tile['row_start'],
            "row_stop" : tile['row_stop'],
            "col_start" : tile['col_start'],
            "col_stop": tile['col_stop']
        }

        res.append(cell_dict)

    return res

def stitch_masks(tiles):
    """
    This function takes in the masks generated and stitches them back into a full image. It returns an array of masks

    : ARGS : 

    tiles : list
        A list of dicts of the tiles from cell detect
    """

    output = np.zeros((tiles[-1]['row_stop'], tiles[-1]['col_stop']), dtype=np.int64)

    for tile in tiles:
        tile['mask'] = tile['mask'].astype(np.int64)
        current_max = np.int64(np.max(output))
        tile['mask'][tile['mask'] != 0] += current_max
        output_slice = output[tile['row_start']: tile['row_stop'], tile['col_start']: tile['col_stop']]
        mask_crop = tile['mask'][:output_slice.shape[0], :output_slice.shape[1]]
        condition = mask_crop != 0
        output_slice[condition] = mask_crop[condition]
        output[tile['row_start']: tile['row_stop'], tile['col_start']: tile['col_stop']] = output_slice
        

    return output

def save_masks(masks, file_path, output_dir):
    """
    This function takes the array of masks from stitch_masks and save it in a folder.

    : ARGS :

    masks : array
        An array of masks created by stitch_masks
    """

    file_name = os.path.splitext(os.path.basename(file_path))[0] + "_mask.tiff"
    output_path = os.path.join(output_dir, file_name)
    tifffile.imwrite(output_path, masks, compression='zstd')

    return

def write_segmentation_results(db_path, file_path, stitch):
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()

    # Look up slide_id by file path
    cursor.execute("SELECT slide_id FROM slides WHERE file_path = ?", (file_path,))
    row = cursor.fetchone()

    if row is None:
        print(f"No slide found for {file_path}")
        conn.close()
        return

    cell_count = int(np.max(stitch))
    slide_id = row[0]
    status = 'Passed'
    error_message = None
    
    try:
        cursor.execute("""INSERT INTO segmentation_results 
            (slide_id, cell_count, diameter_used, tile_size, 
            tile_overlap, segment_status, error_message, processed_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
            (slide_id, cell_count, args.diameter, tile_size,
            tile_overlap, status, error_message, datetime.now()))
        
        # Update pipeline status
        cursor.execute("UPDATE pipeline_status SET segmentation = ? WHERE slide_id = ?",
                      (status, slide_id))
        conn.commit()
    except Exception as e:
        status = 'Failed'
        error_message = str(e)
        cursor.execute("""INSERT INTO segmentation_results 
            (slide_id, segment_status, error_message, processed_at)
            values (?, ?, ?, ?)""",
            (slide_id, status, error_message, datetime.now()))
        print(f"Error: {e}")
        conn.commit()
    finally:
        conn.close()

if __name__ == "__main__":
    folder_name = args.project
    db_path = DB_PATH
    
    print("Scanning for files...")
    files = scan_for_files(f"{ISILON_BASE}/{folder_name}")
    print(f"Found {len(files)} files")
    project_path = f"{ISILON_BASE}/{folder_name}"
    masks_dir = os.path.join(project_path, 'masks')
    os.makedirs(masks_dir, exist_ok=True)
    print(f"Mask directory ready: {masks_dir}")

    for file in files:
        if is_already_processed(db_path, file, 'segmentation_results'):
            print(f"Skipping {os.path.basename(file)}: already processed.")
            continue
        print(f"Segmenting {os.path.basename(file)}...")
        dapi = extract_dapi_channel(file)
        tiles = tile_image(dapi)
        cells = detect_cells(tiles)
        stitch = stitch_masks(cells)
        output_dir = os.path.join(os.path.dirname(file), 'masks')
        save_masks(stitch, file, output_dir)
        write_segmentation_results(db_path, file, stitch)

    print("Done!")