# =============================================================================
# spatial_analysis.py
# Author: Henry Boyes
# Institution: Cleveland Clinic
# Date: 3/26/2026
# Version: v0.3.0
# Contact: boyeshenry@gmail.com
# Description: This script takes the phenotyped AnnData files, builds a spatial graph, performs neighborhood enrichment analysis,
# computes co-occurrence scores, runs Ripley's statistics and exports the spatial metrics.
# =============================================================================

import os
import argparse
import numpy as np 
import sqlite3
import pandas as pd
import anndata as ad 
import squidpy as sq
import seaborn as sns
import matplotlib.pyplot as plt
from utils import setup_logging

ISILON_BASE = os.environ.get("AKOYA_ISILON")
DB_PATH = os.environ.get("AKOYA_DB")

parser = argparse.ArgumentParser(description="Project folder name")
parser.add_argument("--project", required=True, type=str, help="Enter the project folder name (case sensitive)")
parser.add_argument("--n_neigh", default=10, type=int, help="Enter the number of neighbors of the cells . Default is 10")
args = parser.parse_args()

def find_slides(cursor, project):
    """
    This function checks if a slide has phenotyping completed. It returns a tuple of slide_id and slide_name

    : ARGS :

    cursor : sqlite3.cursor
        Active database cursor for executing queries

    project : str
        The project/dir name, given by argparse

    
    : RETURNS :

    res : list
        A list of tuples of slide_id and slide_name for the project
    """

    project_filter = f"%{project}%"

    cursor.execute("""SELECT s.slide_id, s.slide_name
    FROM slides s
    JOIN pipeline_status ps ON
        s.slide_id = ps.slide_id
    where ps.phenotyping ='Complete'
    AND ps.spatial_analysis != 'Complete'
    AND s.file_path LIKE ?;""", (project_filter,))

    res = cursor.fetchall()

    if res:
        return res
    else:
        print('No data found! Please check the database.')

def spatial_graphing(adata, n_neigh):
    """
    This function calls on squidpy's gr.spatial_neighbors to create a spatial graph for analysis

    : ARGS :

    adata : AnnData object
        An AnnData object that has been processed by phentyping.py

    n_neigh : int, optional (default=10)
        The number of neighbors for n_neigh spatial graphing

    : RETURNS :

    adata : AnnData Object
        An AnnData object with spatial graphing complete
    """

    sq.gr.spatial_neighbors(adata, n_neighs=n_neigh, coord_type='generic', copy=False)

    return adata

def neighborhood_enrichment(adata):
    """
    This function performs neighborhood enrichment on the spatial graph

    : ARGS :

    adata : AnnData object
        AnnData object with spatial graphing completed

    : RETURNS : 

    adata : AnnData object
        AnnData object with neighborhood enrichment
    """

    sq.gr.nhood_enrichment(adata, cluster_key="leiden", n_perms=1000, show_progress_bar=True, seed=1234, copy=False)

    return adata

def compute_co_occurrence(adata):
    """
    This function takes the neighborhood enriched AnnData and computes the co-occurence of the cells within

    : ARGS : 

    adata : AnnData object
        An AnnData object that has undergone neighborhood enrichment

    : RETURNS : 
                                    
    adata : AnnData object
        An AnnData object with co-occurnce computed
    """

    sq.gr.co_occurrence(adata, cluster_key="leiden", spatial_key='spatial', show_progress_bar=True, 
    interval=adata.uns['co_occurrence_interval'], copy=False)

    return adata
                                                  

def ripley_stats(adata, n_neigh):
    """
    This function calculates the Ripley's Statistics for point processes for the AnnData object

    : ARGS :

    adata : AnnData object
        An AnnData object that has the co-occurence calculated


    : RETURNS :

    adata : AnnData object
        An AnnData object with Ripley's Statistics calculated
    """

    modes = ["F", "G", "L"]

    for mode in modes:
        sq.gr.ripley(adata, cluster_key='leiden', mode=mode,  n_simulations=1000, 
        n_neigh=n_neigh, seed=1234, copy=False)

    return adata

def export_metrics(adata, output_dir, slide_id, slide_name):
    """
    This function saves the analysis results into 3 .csv files and a final .h5ad file into a final_output directory

    : ARGS :

    adata : AnnData object
        The analyzed AnnData object

    output_dir : str
        The dir to save the results in

    slide_id : int
        The slide_id from the database

    slide_name : str
        The slide name generated by the Akoya PCF
    """
    modes = ["F", "G", "L"]

    leiden_labels = adata.obs['leiden'].unique()

    anndata_dir = os.path.join(output_dir, 'anndata')
    nhood_dir = os.path.join(output_dir, 'neighborhood_enrichment')
    ripley_dir = os.path.join(output_dir, 'ripley')
    co_occ_dir = os.path.join(output_dir, 'co_occurrence')

    for d in [anndata_dir, nhood_dir, ripley_dir, co_occ_dir]:
        os.makedirs(d, exist_ok=True)

    # Save zscores
    zscore_df = pd.DataFrame(adata.uns["leiden_nhood_enrichment"]["zscore"], index=leiden_labels, columns=leiden_labels)
    pval_df = pd.DataFrame(adata.uns["leiden_nhood_enrichment"]["pvalue"], index=leiden_labels, columns=leiden_labels)

    output = os.path.join(nhood_dir, f"{slide_id}_{slide_name}_zscore.csv")
    zscore_df.to_csv(output)

    output = os.path.join(nhood_dir, f"{slide_id}_{slide_name}_pvalue.csv")
    pval_df.to_csv(output)

    # Save Ripley's Stats
    for mode in modes:
        export = adata.uns[f"leiden_ripley_{mode}"]
        output = os.path.join(ripley_dir, f"{slide_id}_{slide_name}_mode_{mode}.csv")
        export[f"{mode}_stat"].to_csv(output)
        output = os.path.join(ripley_dir, f"{slide_id}_{slide_name}_mode_{mode}_pvalues.csv")
        pd.DataFrame(export["pvalues"], index=leiden_labels, columns=export["bins"]).to_csv(output)


    # Save OCC 
    intervals = adata.uns["leiden_co_occurrence"]["interval"][:-1]

    co_occ_df = pd.DataFrame()

    for idx, interval_val in enumerate(intervals):
        df = pd.DataFrame(adata.uns["leiden_co_occurrence"]["occ"][:, :, idx], index=leiden_labels, columns=leiden_labels)
        df["interval"] = interval_val
        co_occ_df = pd.concat([co_occ_df, df])
        
    

    co_occ_df = pd.melt(co_occ_df, id_vars="interval", value_vars=leiden_labels, value_name="score", var_name="cluster_1")
    
    output = os.path.join(co_occ_dir, f"{slide_id}_{slide_name}_co_occ.csv")
    co_occ_df.to_csv(output)

    # Save Final AnnData object
    output = os.path.join(anndata_dir, f"{slide_id}_{slide_name}_final.h5ad")
    adata.write_h5ad(output)

    return

def plot_spatial_qc(adata, slide_id, spatial_qc_dir):
    """
    This function generates QC plots for the spatial analysis

    : ARGS : 

    adata : AnnData object
        An AnnData object with spatial analysis features

    slide_id : int
        The slide id in the database
    
    spatial_qc_dir : str
        The output dir for the saved plots
    """
    leiden_labels = adata.obs['leiden'].unique()

    plt.figure()
    sns.heatmap(adata.uns["leiden_nhood_enrichment"]["zscore"], cmap="coolwarm", cbar=True, xticklabels=leiden_labels, 
    yticklabels=leiden_labels)
    plt.title(f"Slide {slide_id} zscore")
    plt.savefig(os.path.join(spatial_qc_dir, f"slide_{slide_id}_zscore.png"))
    plt.close()

    plt.figure()
    sns.lineplot(adata.uns["leiden_ripley_L"], x='bins', y='stats', hue='leiden')
    plt.title(f"Slide {slide_id} Ripley's L Curve")
    plt.savefig(os.path.join(spatial_qc_dir, f"slide_{slide_id}_ripleys_L_curve.png"))
    plt.close()

    plt.figure()
    sns.heatmap(np.mean(adata.uns["leiden_co_occurrence"]["occ"], axis=2), cmap="viridis", cbar=True, xticklabels=leiden_labels,
    yticklabels=leiden_labels)
    plt.title(f"Slide {slide_id} co occurrence")
    plt.savefig(os.path.join(spatial_qc_dir, f"slide_{slide_id}_co_occ.png"))
    plt.close()

def update_pipeline_status(cursor, status, slide_id):
    """
    This function updates the pipelines status

    : ARGS : 

    cursor : sqlite3.cursor
        Active database cursor for executing queries

    status : str
        The status of the pipeline stage
    
    slide_id : int
        The integer primary key from the akoya.db
    """

    cursor.execute("UPDATE pipeline_status SET spatial_analysis = ? WHERE slide_id = ?", (status, slide_id))

    return

if __name__ == "__main__":
    folder_name = args.project
    n_neigh = args.n_neigh
    db_path = DB_PATH
    project_path = f"{ISILON_BASE}/{folder_name}"

    output_dir = os.path.join(project_path, 'spatial')
    os.makedirs(output_dir, exist_ok=True)
    spatial_qc_dir = os.path.join(output_dir, "spatial_qc")
    os.makedirs(spatial_qc_dir, exist_ok=True)
    
    log_dir = os.path.join(project_path, 'logs')

    logger = setup_logging(folder_name, log_dir)
    
    logger.info("Directories Ready")

    conn = sqlite3.connect(db_path, timeout=30)
    cursor = conn.cursor()

    logger.info("Fetching slides")
    slides = find_slides(cursor, folder_name)
    if not slides:
        exit()

    for slide in slides:
        try:
            slide_id, slide_name = slide
            file_path = os.path.join(project_path, 'phenotyping', f"slide_{slide_id}_{slide_name}_phenotyped.h5ad")
            adata = ad.read_h5ad(file_path)
            
            cursor.execute("SELECT diameter_used FROM segmentation_results WHERE slide_id=?", (slide_id, ))
            diameter = cursor.fetchone()[0]
            adata.uns["cell_diameter"] = diameter
            adata.uns["co_occurrence_interval"] = np.arange(diameter, 11 * diameter, diameter)

            logger.info(f"Performing Spatial Graphing for {slide_id}")
            adata = spatial_graphing(adata, n_neigh)
            logger.info("Performing Neighborhood Enrichment")
            adata = neighborhood_enrichment(adata)
            logger.info("Computing co-occurrence")
            adata = compute_co_occurrence(adata)
            logger.info("Calculating Ripley's Statistics")
            adata = ripley_stats(adata, n_neigh)
            logger.info("Exporting data")
            export_metrics(adata, output_dir, slide_id, slide_name)
            logger.info("Saving QC plots")
            plot_spatial_qc(adata, slide_id, spatial_qc_dir)
            

            status = "Complete"

            update_pipeline_status(cursor, status, slide_id)
            conn.commit()

        except Exception as e:
            logger.error(f"Slide {slide_id} failed with error: {e}")
            status = "Failed"
            try:
                update_pipeline_status(cursor, status, slide_id)
                conn.commit()
            except Exception as db_err:
                logger.error(f"DB update failed: {db_err}")
    
    conn.close()

    logger.info("Done!")